# Generated by Django 5.0.3 on 2024-07-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
