# Generated by Django 5.0.3 on 2025-05-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_category_image_size_storecategory_storetype_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.AlterModelOptions(
            name='storecategory',
            options={'ordering': ('name',), 'verbose_name': 'Store Category', 'verbose_name_plural': 'Store Categories'},
        ),
    ]
