# Generated by Django 5.0.3 on 2024-07-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_meal_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
