# Generated by Django 5.0.3 on 2024-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_alter_meal_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="percentage",
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name="meal",
            name="price",
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
