# Generated by Django 5.0.3 on 2025-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_category_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, default='th-large', max_length=50),
        ),
    ]
