# Generated by Django 5.0.3 on 2024-07-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_alter_meal_percentage_alter_meal_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="account_number",
            field=models.CharField(blank=True, max_length=500, verbose_name="account"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="bank",
            field=models.CharField(blank=True, max_length=500, verbose_name="bank"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="iban",
            field=models.CharField(blank=True, max_length=500, verbose_name="iban"),
        ),
    ]
