# Generated by Django 5.0.3 on 2024-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curtomers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="location",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="localização"
            ),
        ),
    ]
