# Generated by Django 5.2 on 2025-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', max_length=2),
        ),
    ]
