# Generated by Django 5.2.1 on 2025-10-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='AOA', max_length=3)),
                ('target_currency', models.CharField(db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'target_currency'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency', '-date'], name='currency_ex_base_cu_ebdec4_idx')],
                'unique_together': {('base_currency', 'target_currency', 'date')},
            },
        ),
    ]
