# Generated by Django 6.0.5 on 2026-05-16 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kudya_platform', '0001_initial'),
        ('services', '0002_country_currency_country_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ride', 'Ride'), ('food_delivery', 'Food Delivery'), ('grocery_delivery', 'Grocery Delivery'), ('package', 'Package Delivery'), ('rental', 'Car Rental')], db_index=True, max_length=30)),
                ('ride_type', models.CharField(blank=True, choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('premium', 'Premium'), ('xl', 'XL'), ('bike', 'Bike'), ('delivery_bike', 'Delivery Bike'), ('women', 'Women Preferred'), ('scheduled', 'Scheduled')], max_length=20)),
                ('base_fare', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=8, max_digits=10)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=10)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=35, max_digits=10)),
                ('delivery_base_fee', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('surge_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudya_platform.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.country')),
            ],
            options={
                'ordering': ['service_type', 'country'],
            },
        ),
    ]
