# Generated by Django 5.2 on 2025-05-09 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0002_emailcampaign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('opened', 'Opened')], default='sent', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emailmarketing.emailcampaign')),
            ],
        ),
    ]
