# Generated by Django 5.2.1 on 2025-06-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('paid', 'Pago'), ('unpaid', 'Não Pago')], default='unpaid', verbose_name='estado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='pedido')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='loja')),
            ],
        ),
    ]
