# Generated by Django 5.0.3 on 2024-07-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_coupon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
    ]
