# Generated by Django 6.0.5 on 2026-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.CharField(default='Africa/Johannesburg', max_length=50),
        ),
    ]
