# Generated by Django 5.2.1 on 2025-10-14 08:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('punctuality', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('care_of_items', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='completed_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Available to accept new deliveries'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='service_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='service_radius_km',
            field=models.IntegerField(default=10, help_text='Service radius in kilometers'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_photo',
            field=models.ImageField(blank=True, upload_to='driver/vehicles/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck'), ('bicycle', 'Bicycle'), ('on_foot', 'On Foot')], default='motorcycle', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('order', 'Product Order'), ('service', 'Service-related Delivery'), ('ride', 'Ride Service')], default='order', max_length=20)),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('delivery_address', models.CharField(max_length=500)),
                ('delivery_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('delivery_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Driver'), ('accepted', 'Accepted by Driver'), ('rejected', 'Rejected by Driver'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pickup_instructions', models.TextField(blank=True)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('special_requirements', models.CharField(blank=True, max_length=200)),
                ('proof_photo', models.ImageField(blank=True, upload_to='delivery_proofs/')),
                ('customer_signature', models.ImageField(blank=True, upload_to='delivery_signatures/')),
                ('delivery_notes', models.TextField(blank=True)),
                ('customer_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer_feedback', models.TextField(blank=True)),
                ('driver_tip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='drivers.driver')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_request', to='order.order')),
            ],
            options={
                'verbose_name': 'Delivery Request',
                'verbose_name_plural': 'Delivery Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
