# Generated by Django 5.0.3 on 2024-07-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_rejected_orders_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="rejected_orders_count",
            new_name="rejected_orders",
        ),
    ]
