# Generated by Django 5.2.1 on 2025-10-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('drivers', '0002_driverlocation_driverrating_driver_average_rating_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='service_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='services.booking'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='delivery_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updates', to='drivers.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='driverrating',
            name='delivery_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rating', to='drivers.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='driverrating',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='drivers.driver'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['driver', '-recorded_at'], name='drivers_dri_driver__946657_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['delivery_request', '-recorded_at'], name='drivers_dri_deliver_50fd50_idx'),
        ),
    ]
