# Generated by Django 5.0.3 on 2024-07-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_rename_rejected_orders_count_driver_rejected_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="make",
            field=models.CharField(blank=True, max_length=500, verbose_name="Model"),
        ),
        migrations.AddField(
            model_name="driver",
            name="plate",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Matricula"
            ),
        ),
    ]
