# Generated by Django 5.0.3 on 2024-07-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_driver_make_driver_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="account_number",
            field=models.CharField(blank=True, max_length=500, verbose_name="account"),
        ),
        migrations.AddField(
            model_name="driver",
            name="bank",
            field=models.CharField(blank=True, max_length=500, verbose_name="bank"),
        ),
        migrations.AddField(
            model_name="driver",
            name="iban",
            field=models.CharField(blank=True, max_length=500, verbose_name="iban"),
        ),
    ]
