# Generated by Django 6.0.5 on 2026-05-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('kudya_platform', '__first__'),
        ('services', '0002_country_currency_country_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='kudya_platform.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='services.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Portuguese'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('courier', 'Courier'), ('merchant', 'Merchant Owner'), ('restaurant', 'Restaurant Owner'), ('doctor', 'Doctor'), ('service_provider', 'Service Provider'), ('host', 'Host'), ('landlord', 'Landlord'), ('agent', 'Property Agent'), ('business_admin', 'Business Account Admin'), ('business_employee', 'Business Employee'), ('support', 'Support Agent'), ('country_admin', 'Country Admin'), ('city_admin', 'City Admin'), ('finance_admin', 'Finance Admin'), ('compliance_admin', 'Compliance Admin'), ('safety_admin', 'Safety Admin'), ('super_admin', 'Super Admin')], db_index=True, default='customer', max_length=30),
        ),
    ]
