# Generated by Django 6.0.5 on 2026-05-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_user_city_user_country_user_is_verified_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('courier', 'Courier'), ('merchant', 'Merchant Owner'), ('restaurant', 'Restaurant Owner'), ('grocery_store_owner', 'Grocery Store Owner'), ('doctor', 'Doctor'), ('clinic_admin', 'Clinic Admin'), ('service_provider', 'Service Provider'), ('host', 'Host'), ('landlord', 'Landlord'), ('agent', 'Property Agent'), ('rental_partner', 'Rental Partner'), ('business_admin', 'Business Account Admin'), ('business_employee', 'Business Employee'), ('support', 'Support Agent'), ('country_admin', 'Country Admin'), ('city_admin', 'City Admin'), ('finance_admin', 'Finance Admin'), ('compliance_admin', 'Compliance Admin'), ('safety_admin', 'Safety Admin'), ('super_admin', 'Super Admin')], db_index=True, default='customer', max_length=30),
        ),
    ]
