# Generated by Django 6.0.5 on 2026-05-16 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_deliveryrequest_service_booking_and_more'),
        ('kudya_platform', '0001_initial'),
        ('services', '0002_country_currency_country_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('ride_type', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('premium', 'Premium'), ('xl', 'XL'), ('bike', 'Bike'), ('delivery_bike', 'Delivery Bike'), ('women', 'Women Preferred'), ('scheduled', 'Scheduled')], default='economy', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('searching', 'Searching for Driver'), ('accepted', 'Accepted'), ('arrived', 'Driver Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_address', models.CharField(max_length=500)),
                ('destination_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='cash', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('share_trip_token', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kudya_platform.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
