# Generated by Django 5.2 on 2025-05-11 17:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_signatureinvite_invited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureinvite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signatureinvite',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
