# Generated by Django 6.0.5 on 2026-05-16 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('merchant', 'Merchant'), ('doctor', 'Doctor'), ('service_provider', 'Service Provider'), ('host', 'Host'), ('landlord', 'Landlord'), ('agent', 'Property Agent'), ('business', 'Business Account'), ('platform', 'Platform')], db_index=True, max_length=20)),
                ('owner_id', models.PositiveIntegerField(db_index=True)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner_type', 'owner_id', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('top_up', 'Top Up'), ('payment', 'Payment'), ('refund', 'Refund'), ('earning', 'Earning'), ('payout', 'Payout'), ('transfer', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
