# Generated by Django 5.0.3 on 2024-07-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_remove_chat_sender_chatmessage"),
        ("order", "0007_alter_order_chat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
