# Generated by Django 6.0.5 on 2026-05-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_country_currency_country_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('food', 'Food'), ('groceries', 'Groceries'), ('rides', 'Rides'), ('package', 'Send Package'), ('car_rental', 'Car Rental'), ('doctors', 'Doctors'), ('services', 'Services'), ('accommodation', 'Accommodation'), ('property', 'Property'), ('wallet', 'Wallet'), ('business', 'Business')], max_length=30, unique=True)),
                ('icon', models.CharField(default='grid', max_length=50)),
                ('route', models.CharField(help_text='Client navigation route', max_length=100)),
                ('gradient_start', models.CharField(default='#3B82F6', max_length=7)),
                ('gradient_end', models.CharField(default='#1D4ED8', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_auth', models.BooleanField(default=False)),
                ('allowed_countries', models.ManyToManyField(blank=True, related_name='platform_modules', to='services.country')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt', 'Portuguese'), ('fr', 'French'), ('es', 'Spanish')], db_index=True, max_length=5)),
                ('value', models.TextField()),
                ('module', models.CharField(db_index=True, default='common', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module', 'key'],
                'unique_together': {('key', 'language', 'module')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='services.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
