# Generated by Django 6.0.5 on 2026-05-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudya_platform', '0001_initial'),
        ('services', '0002_country_currency_country_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryComplianceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_consultations_allowed', models.BooleanField(default=False)),
                ('prescriptions_allowed', models.BooleanField(default=False)),
                ('required_doctor_documents', models.JSONField(blank=True, default=list)),
                ('medical_license_verification_required', models.BooleanField(default=True)),
                ('data_privacy_policy', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('refund_policy', models.TextField(blank=True)),
                ('tax_vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_rules', models.JSONField(blank=True, default=dict)),
                ('patient_data_retention_days', models.PositiveIntegerField(default=3650)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_settings', to='services.country')),
            ],
            options={
                'ordering': ['country__name'],
            },
        ),
    ]
