# Generated by Django 6.0.5 on 2026-05-16 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kudya_platform', '0001_initial'),
        ('services', '0002_country_currency_country_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('food', 'Food Delivery'), ('grocery', 'Grocery'), ('ride', 'Ride Hailing'), ('package', 'Package Delivery'), ('car_rental', 'Car Rental'), ('doctor', 'Doctor Booking'), ('service', 'Professional Service'), ('accommodation', 'Accommodation'), ('rental_lead', 'Long-Term Rental Lead'), ('property_sale', 'Property Sale Lead')], max_length=30)),
                ('provider_type', models.CharField(blank=True, max_length=50)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Fee'), ('subscription', 'Monthly Subscription'), ('per_lead', 'Pay Per Lead'), ('featured', 'Featured Listing Fee')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=10)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudya_platform.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='services.country')),
            ],
            options={
                'ordering': ['service_type', 'country'],
            },
        ),
    ]
