# Generated by Django 5.2.1 on 2025-06-04 22:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Desconto')),
                ('order_count', models.IntegerField(default=0, verbose_name='Contagem de Pedidos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Endereco')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Entrega')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Desconto')),
                ('use_current_location', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='localizacao')),
                ('status', models.IntegerField(choices=[(1, 'PROCESSANDO'), (2, 'Pedido Pronto'), (3, 'A caminho'), (4, 'Entregue'), (5, 'Rejeitado'), (6, 'Verificado')], verbose_name='stado')),
                ('payment_method', models.CharField(max_length=50, verbose_name='método de pagamento')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='pegar em')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Fatura PDF')),
                ('secret_pin', models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN Secreto')),
                ('driver_commission_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('proof_of_payment_store', models.FileField(blank=True, null=True, upload_to='proof_of_payment/store/', verbose_name='Prova de Pagamento ao Shop')),
                ('proof_of_payment_driver', models.FileField(blank=True, null=True, upload_to='proof_of_payment/driver/', verbose_name='Prova de Pagamento ao Motorista')),
                ('payment_status_store', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10, verbose_name='Status de Pagamento ao Store')),
                ('payment_status_driver', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10, verbose_name='Status de Pagamento ao Motorista')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('driver_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.coupon', verbose_name='Cupom')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='cliente')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='motorista')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product', verbose_name='Refeição')),
            ],
            options={
                'verbose_name': 'Detalhe do pedido',
                'verbose_name_plural': 'Detalhes dos pedidos',
            },
        ),
    ]
