# Generated by Django 5.0.3 on 2024-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_driver_commission_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Cozinhando"),
                    (2, "Pedido Pronto"),
                    (3, "A caminho"),
                    (4, "Entregue"),
                    (5, "Rejeitado"),
                ],
                verbose_name="stado",
            ),
        ),
    ]
