# Generated by Django 5.0.3 on 2024-07-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_remove_chat_sender_chatmessage"),
        ("order", "0006_alter_order_address_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="chat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_chat",
                to="info.chatmessage",
            ),
        ),
    ]
