# Generated by Django 5.0.3 on 2024-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_order_delivery_fee_order_delivery_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="localizacao"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="use_current_location",
            field=models.BooleanField(default=False),
        ),
    ]
