# Generated by Django 6.0.5 on 2026-05-16 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_deliveryrequest_service_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('package_type', models.CharField(choices=[('envelope', 'Small Envelope'), ('small', 'Small Parcel'), ('medium', 'Medium Parcel'), ('large', 'Large Parcel'), ('fragile', 'Fragile Item'), ('document', 'Document Delivery')], default='small', max_length=20)),
                ('urgency', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('same_day', 'Same Day')], default='standard', max_length=20)),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('dropoff_address', models.CharField(max_length=500)),
                ('dropoff_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('dropoff_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('package_notes', models.TextField(blank=True)),
                ('package_photo', models.ImageField(blank=True, upload_to='packages/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('searching', 'Searching Courier'), ('accepted', 'Accepted'), ('pickup_confirmed', 'Pickup Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='requested', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('proof_of_pickup', models.ImageField(blank=True, upload_to='package_proofs/')),
                ('proof_of_delivery', models.ImageField(blank=True, upload_to='package_proofs/')),
                ('pickup_otp', models.CharField(blank=True, max_length=6)),
                ('delivery_otp', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_deliveries', to='drivers.driver')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
